import React from "react";
import { Dialog } from "@headlessui/react";
import Button from "../UI/Button";
import { DownloadIcon, X } from "lucide-react";

export default function ReportPreviewModal({
  isOpen,
  onClose,
  report,
  onDownload,
}) {
  return (
    <Dialog
      open={isOpen}
      onClose={onClose}
      className="fixed z-50 inset-0 overflow-y-auto"
    >
      <div className="flex items-center justify-center min-h-screen px-4">
        <Dialog.Overlay className="fixed inset-0 bg-black opacity-30" />
        <div className="relative bg-white rounded-lg max-w-3xl w-full p-6 shadow-xl z-10">
          <div className="flex justify-between items-center mb-4">
            <Dialog.Title className="text-lg font-semibold">
              {report?.name}
            </Dialog.Title>
            <button onClick={onClose}>
              <X className="w-5 h-5 text-gray-600 hover:text-gray-900" />
            </button>
          </div>

          {/* Replace this content with actual report content */}
          <div className="max-h-[400px] overflow-y-auto border rounded p-4 bg-gray-50">
            <p>
              <strong>Type:</strong> {report?.type}
            </p>
            <p>
              <strong>Generated By:</strong> {report?.user}
            </p>
            <p>
              <strong>Date:</strong> {report?.date}
            </p>
            <p className="mt-4 text-sm text-gray-600">
              This is a preview of the report content. You can fetch actual data
              or embed a PDF here.
            </p>
          </div>

          <div className="flex justify-end mt-6 gap-2">
            <Button variant="secondary" onClick={onClose}>
              Close
            </Button>
            <Button
              variant="primary"
              icon={<DownloadIcon className="h-4 w-4 mr-1" />}
              onClick={onDownload}
            >
              Download
            </Button>
          </div>
        </div>
      </div>
    </Dialog>
  );
}
